aws/aws-kotlin-repo-tools

build-plugins/build.gradle.kts, build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt, gradle/libs.versions.toml
n/a
Migrate repeated publishing logic into build plugin/dsl.
=> import publishing logic

brazil/transforms.json
=> fix: use jvm artifact for resolves conflict transform

brazil/transforms.json
n/a
Use JVM variant for MV override.
=> fix: use jvm version of MV override

build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
Allows android publication to support **aws-crt-kotlin**
=> misc: allow android publication

README.md, build.gradle.kts, scripts/release.sh
Adds build logic for publishing to an S3 bucket.
=> publish releases to private s3 maven repo

scripts/ci.py
*Issue #, if available:* N/A
*Description of changes:* Added the checkout pr command to the CI script
=> feat: add checkout pr command to ci script

README.md
Adding more detail to the release instructions
=> misc: update release instructions

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/ArtifactSizeMetricsPlugin.kt
=> fix: specify ASM bucket (ASM plugin)

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/AnalyzeArtifactSizeMetrics.kt, build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/PutArtifactSizeMetricsInCloudWatch.kt
=> misc: small bug fixes

build-plugins/kmp-conventions/build.gradle.kts, gradle.properties
=> misc: upgrade to Kotlin 2.0.10

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
=> fix: Add dynamodb-mapper-schema-generatorPluginMarkerMaven to allow list

build-plugins/kmp-conventions/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureTargets.kt
=> misc: remove explicit kotlin("stdlib") dependency application

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
=> fix: set destination directory of emptyJar task

.github/actions/checkout-head/action.yml
=> misc: enable using `kn-main` in CI

.github/actions/checkout-head/action.yml
=> kn: enable checking out submodules recursively

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
=> misc: Update license to Apache-2.0

build-plugins/build-support/build.gradle.kts, build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
=> misc: prepare to merge `kn-main` back into `main`

.github/actions/artifact-size-metrics/show-results/action.yml
=> misc: add closing brace

gradle/libs.versions.toml
=> misc: upgrade to latest version of Nexus publish plugin

CODEOWNERS, gradle/libs.versions.toml
(none)
Upgrade to Smithy **1.60.2**. Also add a **CODEOWNERS** file so that at least one **aws-sdk-kotlin-sde** reviewer is required for every PR.
=> chore: smithy upgrade

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
=> misc: make nexus urls configurable

build-plugins/build-support/build.gradle.kts, build.gradle.kts, gradle.properties, gradle/libs.versions.toml, settings.gradle.kts
(none)
This change re-adds Kotlin 2.2.0 support to **aws-kotlin-repo-tools**!
=> chore: revert "chore: revert "feat: upgrade to Kotlin 2.2.0 (#96)" (#99)"

build-plugins/build-support/build.gradle.kts, build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt, build.gradle.kts, gradle/libs.versions.toml
=> kn: merge from main, add mingwX64 as an allowed publication

gradle/libs.versions.toml
=> misc: upgrade to latest version of S3

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
=> misc: configure `applyMavenCentralRules`

.github/workflows/continuous-integration.yml, .github/workflows/lint.yml, .github/workflows/merge-main.yml
(none)
This change adds minimal permissions to our GitHub workflows.
=> chore: add missing permissions for GitHub workflows

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
=> Allow publishing K/N artifacts to test namespace
