brazil/transforms.json

N/A
Bump to using KotlinxCoroutines 1.7.x internally to resolve major version conflicts.

misc: use KotlinxCoroutines* 1.7.x internally

---

build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ProjectExt.kt

n/a
Fixes exception when property doesn't exist in any of the property containers

fix: extra throws exception instead of returning null

---

build-plugins/build.gradle.kts
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/CodeStyle.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/LintRules.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/KmpDefaultsPlugin.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/KmpProjectExt.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/util/ProjectExt.kt
build.gradle.kts
ktlint-rules/build.gradle.kts

n/a
Create the `ktlint` and `ktlintFormat` tasks and include our custom `ktlint-rules` by default. This works by adding our custom lint rules project as a runtime dependency of the plugin. The buildscript classpath is then included as the classpath for the ktlint exec task. This allows dowstream projects to define additional project specific rules should the need arise by simpling adding them to the buildscript classpath
e.g.
```kotlin
buildscript {
classpath("aws.sdk.kotlin:build-plugins")   // includes ktlint-rules
classpath(project(":my-custom-rules"))
}
```

configure ktlint with custom rules

---

build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureTargets.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/KmpDefaultsPlugin.kt

n/a
* Move where we apply `subprojects` which makes `configureKmpTargets()` re-usable for a single project.

refactor: make kmp target configuration reusable

---

brazil/transforms.json

n/a
* Latest `kat` version allows wildcard dependency versions, update deps where appropriate to use this so that we don't have to update this file for every patch version that is going to map to the same brazil MV anyway
* Add new MV overrides on a per/dependency basis. `OkHttpCoroutines` depends on `KotlinxCoroutines` 1.6.x, the SDK depends on 1.7.x, this adds an explicit override for this specific version of that dependency.

refactor: update transforms to use wildcards and add explicit MV overrides for specific deps

---

scripts/ci.py

support for: https://github.com/awslabs/aws-sdk-kotlin/pull/1063
* Adds a new python script usable in CI by our repos to manage the correct branch version. This is still a bit of a WIP but it handles the logic we need that CRT builder provides today to figure out branches in PRs.

add CI utils for managing dependency branches

---

.github/actions/checkout-head/action.yml

Adds a new composite action that works like `actions/checkout` but fetches the corresponding head ref if it exists, falling back to base ref as necessary. This removes the need for GH actions to rely on CRT builder for pulling the correct version of a dependency.

re-usable composite action to pull dependency versions

---

build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureTargets.kt

fix: `configureLinux` disable tests

---

build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt

- Add `codegen` and `codegen-testutils` to allowed publications list
- Log a warning when skipping publications

fix: allow codegen/codegen-testutils publication and log warning

---

build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureTargets.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/IdeUtils.kt

Adds support for a Gradle property `aws.kotlin.native` to control building native targets such as `linuxx64`

feat: Add `NATIVE_ENABLED` boolean flag controlled by `aws.kotlin.native` property

---

build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureTargets.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/IdeUtils.kt

* Remove `aws.kotlin.ide.jvmAndCommonOnly` property as this has weird semantics with individual target enable/disable.
* Add `aws.kotlin.jvm` property for conditional enable/disable of JVM target.
* Pull these properties using our extension function which will look for `local.properties` file in several places (including `~/.sdkdev/local.properties` which allows defining properties in one place that will affect all projects/builds).

fix: use all property sources for kmp target enabled properties

---

brazil/transforms.json

Add more resolves-conflict-dependencies rules to remove the hardcoded rules in the internal transformation tool. Wildcards are also supported now.

fix: add more resolvesConflictDependencies rules

---

brazil/transforms.json

n/a
Add dependency transform for Atomicfu 0.23.1. I've left 0.22.0 in place for now as they can coexist and this will keep current builds functioning.

add atomicfu 0.23.1

---

build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt

workaround for https://github.com/gradle/gradle/issues/26091
Workaround for Gradle 8.5 upgrade having issues with task dependencies and signing
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem was found with the configuration of task ':bom:signVersionCatalogPublication' (type 'Sign').
- Gradle detected a problem with the following location: '/codebuild/output/src1917448208/src/smithy-kotlin/bom/build/distributions/bom-1.0.5-javadoc.jar.asc'.
Reason: Task ':bom:publishBomPublicationToTestLocalRepository' uses this output of task ':bom:signVersionCatalogPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. …
```

fix: workaround for gradle 8+ dependency issues

---

build-plugins/build.gradle.kts
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/SmithyBuildExtension.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/SmithyBuildPlugin.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/dsl/ProjectExtensions.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/dsl/SmithyBuildPluginSettings.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/dsl/SmithyKotlinPluginSettings.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/dsl/SmithyProjection.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/dsl/Utils.kt
build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/tasks/GenerateSmithyBuild.kt
build-plugins/src/test/kotlin/aws/sdk/kotlin/gradle/codegen/GenerateSmithyBuildTaskTest.kt
build-plugins/src/test/kotlin/aws/sdk/kotlin/gradle/codegen/SmithyBuildPluginTest.kt
build.gradle.kts
gradle/libs.versions.toml
ktlint-rules/build.gradle.kts
settings.gradle.kts

Adds a new plugin and DSL that wraps the newer smithy gradle base plugin to dynamically define a `smithy-build.json`. This is largely the same as our existing [plugin](https://github.com/awslabs/aws-sdk-kotlin/blob/main/gradle/sdk-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/CodegenPlugin.kt) with some minor refactoring to do things in a more gradle friendly way and adapt to the new smithy plugin.
There is also some cleanup to our buildscript, ability to publish the plugin locally, etc.

feat: codegen plugin

---

README.md
scripts/release.sh

Add additional sanity check in the release script that we are building a tag and that the HEAD commit matches that tag.

fix: verify tag is being built and released

---

build-plugins/build-support/build.gradle.kts
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/ArtifactSizeMetricsPlugin.kt
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/PutArtifactSizeMetricsInCloudWatch.kt
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/SaveArtifactSizeMetrics.kt
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/util/ProjectExt.kt

N/A
Add new task to save artifact size metrics using gradle plugin.
See: https://github.com/awslabs/aws-crt-kotlin/pull/102#discussion_r1579700613
Also some minor simplifications 

feat: save artifact size metrics task

---

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/AnalyzeArtifactSizeMetrics.kt

N/A
Readability improvements to the artifact size metrics comment/table(s)

fix: readability improvements to artifact size metrics

---

build-plugins/kmp-conventions/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureTargets.kt

Fixes an error in smithy-kotlin:
```
Kotlin Source Set 'jvmAndNativeMain' is included in compilations of Kotlin Targets: 'jvm', 'linuxX64'
but it doesn't depend on 'commonMain'
```

fix: make custom source sets depend on common

---

.github/actions/setup-kat/action.yml

misc: add setup-kat action

---

README.md
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
build-plugins/smithy-build/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/dsl/SmithyKotlinPluginSettings.kt

Closes https://github.com/awslabs/aws-kotlin-repo-tools/issues/49

docs: rename `awslabs/smithy-kotlin` to `smithy-lang/smithy-kotlin`

---

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/AnalyzeArtifactSizeMetrics.kt
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/ArtifactSizeMetricsPlugin.kt
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/CollectDelegatedArtifactSizeMetrics.kt
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/PutArtifactSizeMetricsInCloudWatch.kt
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/util/ProjectExt.kt
build-plugins/kmp-conventions/build.gradle.kts
build-plugins/smithy-build/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/SmithyBuildExtension.kt
build-plugins/smithy-build/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/SmithyBuildPlugin.kt
build-plugins/smithy-build/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/dsl/SmithyKotlinPluginSettings.kt
build-plugins/smithy-build/src/main/kotlin/aws/sdk/kotlin/gradle/codegen/dsl/Utils.kt
gradle.properties
gradle/libs.versions.toml
ktlint-rules/src/main/kotlin/software/aws/ktlint/rules/MultilineIfElseBlockRule.kt

misc: Upgrade to Kotlin 2.1.0

---

.github/actions/setup-kat/action.yml

awscli install via apt-get started failing very recently with an error: `Package 'awscli' has no installation candidate`. Let's migrate to `snap` since that's a recommended approach by the CLI team: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

fix: install aws-cli using `snap`

---

build-plugins/kmp-conventions/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureIosSimulator.kt
build-plugins/kmp-conventions/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureTargets.kt

kn: commonize iOS simulator configuration

---

build-plugins/kmp-conventions/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureIosSimulator.kt

kn: Create iOS simulator boot and shutdown tasks in root project

---

.github/workflows/continuous-integration.yml
.github/workflows/lint.yml

feat: use custom gradle URL

---

.github/actions/configure-gradle/action.yml
gradle/wrapper/gradle-wrapper.properties

**We were using gradle to change the gradle distribution URL. That's fine and works, but the purpose of changing the URL is to avoid gradle outages. If we use gradle to change the URL, a fresh install of gradle needs to be downloaded first, from the default distribution URL, which would fail if there's an outage.**

fix: don't use gradle to change gradle distribution URL

---

.github/actions/emit-metrics/action.yml
.github/actions/setup-kat/action.yml
.github/workflows/continuous-integration.yml

(none)
Previously, the **emit-metrics** action attempted to verify **kat** was installed by executing `which kat` but, unfortunately, `which` is not installed on GH action runners by default and installing it is unnecessary overhead. Thus, replaced that check with a simple `kat version` which will achieve the same outcome without relying on `which`.
Also updated the **setup-kat** action to emit more information about paths (should assist in future debugging) and to silence the AWS CLI progress meter (which is less useful in headless environments anyway).
Also upgraded our invocations of `actions/cache@v2` to `v4` since [`v2` is now EOL](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-act …

chore: fix emit-metrics integration with kat

---

.github/actions/setup-kat/action.yml

(none)
Previously, **kat** was installed in `$PWD` which tends to be the path into which repos will be cloned, causing the existing contents to be deleted. To improve resilience and allow **kat** to be installed _before_ source code is checked out, this PR changes the **kat** install dir to `$HOME/kat`. The unzipped binary path is still added to `$PATH`/`$GITHUB_PATH` as before so existing workflows _should_ be unaffected.

chore: install the kat tool in a dedicated home directory instead of using $PWD

---

.github/actions/merge-main/action.yml
.github/scripts/merge-main.sh
.github/workflows/merge-main.yml

- Adds a GH action for merging main into feature branches
- Adds a workflow do it on a schedule or by manual workflow run

feat: main to feature branches merge

---

.github/actions/merge-main/action.yml
.github/scripts/merge-main.sh

N/A
Not using `fetch-depth: 0` when calling `actions/checkout@v4` was causing issues while merging:
`fatal refusing to merge unrelated histories`

fix: merge main action fetch with depth 0

---

.github/actions/merge-main/action.yml
.github/workflows/merge-main.yml

N/A
Handles merge conflicts gracefully i.e. won't fail and exit after only one failed merge
See: https://github.com/awslabs/aws-sdk-kotlin/actions/runs/13917367841/job/38942757708

fix: gracefully handle merge conflicts in main to feature branches action

---

scripts/ci.py

misc: fallback to base branch in `ci.py set-branch`

---

.github/actions/artifact-size-metrics/show-results/action.yml

misc: commonize "Show Results" artifact-size-metrics step

---

build-plugins/build-support/build.gradle.kts
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/CodeStyle.kt
build.gradle.kts
gradle/libs.versions.toml

(none)
Slimmed down version of #70 that focuses strictly on eliminating this compiler warning:
```
w: The artifact `org.jetbrains.kotlin:kotlin-compiler-embeddable` is present in the build classpath along Kotlin Gradle plugin.
This may lead to unpredictable and inconsistent behavior.
For more details, see: https://kotl.in/gradle/internal-compiler-symbols
```

fix: stop including embedded compiler in ktlint tasks

---

.github/actions/merge-main/action.yml
.github/workflows/merge-main.yml

SDK-KT-610
Need to assume the CI role to bypass branch protection rules

fix: use CI user PAT to bypass branch protections

---

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/CollectDelegatedArtifactSizeMetrics.kt

N/A
Collect artifact size metrics for private repos as well.

misc: collect artifact size metrics for private repos

---

build-plugins/kmp-conventions/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureTargets.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/229
This change adds support for Kotlin/Native Windows compilation by configuring the `mingwX64` target when applicable.
This change also removes most support for cross-compilation as it presents too many challenges during development while still not providing a streamlined way to test the built binaries. Kotlin/Native targets will now build only on a host with a matching OS (although different _architectures_ may still be cross-compiled on a single host).
**Companion PR**: https://github.com/awslabs/aws-crt-kotlin/pull/152

feat: Kotlin/Native Windows compilation

---

build-plugins/build-support/build.gradle.kts
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/CollectDelegatedArtifactSizeMetrics.kt

N/A
Something about the `getObjectAsText` function having an S3 client as the receiver or as an argument causes the `Could not create task ':collectDelegatedArtifactSizeMetrics'.` to happen.
<details>
<summary>See full stack trace</summary>
```
Could not create task ':collectDelegatedArtifactSizeMetrics'.
Could not create task of type 'CollectDelegatedArtifactSizeMetrics'.
Could not generate a decorated class for type CollectDelegatedArtifactSizeMetrics.
aws/smithy/kotlin/runtime/client/SdkClient
aws.smithy.kotlin.runtime.client.SdkClient
* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
* Exception is: …
```

fix: intellij collectDelegatedArtifactSizeMetrics issue

---

build.gradle.kts
gradle.properties
gradle/libs.versions.toml
settings.gradle.kts

This reverts commit bdb40dcc24b522ab498a118739c264f3160cbc3d.
Revert Kotlin 2.2.0 upgrade so we can release Smithy upgrade and Maven publishing changes.

chore: revert "feat: upgrade to Kotlin 2.2.0 (#96)"

---

build-plugins/build-support/build.gradle.kts
gradle/libs.versions.toml

(none)
This change pins the SDK version to a specific revision to avoid issues when a new release is _partially published_ on Maven Central.

chore: pin SDK client versions to avoid non-deterministic build failures

---

build-plugins/build-support/build.gradle.kts
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/plugins/artifactsizemetrics/ArtifactSizeMetricsPlugin.kt
gradle/libs.versions.toml

n/a
- Migrated to jreleaser plugin
- Added task to create placeholder JAR for version catalogs

misc: migrate to jreleaser

---

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt

(none)
The publish task now emits warning messages when the JReleaser environment variables aren't set but that's the majority of our builds. Lowering this message to info-level to clean up Gradle build output in the default case.

fix: lower JReleaser configuration warnings to info

---

build-plugins/build-support/build.gradle.kts
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
build.gradle.kts
gradle/libs.versions.toml

finishing the revert that was started in https://github.com/awslabs/aws-sdk-kotlin/pull/1656 by adding back `configureNexus`. This will allow us to upgrade to the latest version of aws-kotlin-repo-tools again. 

fix: add back `configureNexus` function

---

build-plugins/kmp-conventions/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureTargets.kt

(none)
This change updates the target configuration logic for multiplatform source sets. Specifically, the `hasNative` flag previously did not resolve to `true` if a project had no **common** or **native** sources. For instance, **smithy-kotlin/kn-main:runtime:auth
:aws-signing-crt** only has a **jvmAndNative** source set but resolves `hasNative = false`. This change fixes that issue.

fix: add hasJvmAndNative as an additional enabler of hasNative

---

gradle.properties

Disable configuration cache to fix an issue encountered while releasing v0.4.39
```
FAILURE: Build failed with an exception.
--
 
* What went wrong:
Execution failed for task ':ktlint-rules:compileKotlin'.
> Error while evaluating property 'disableMultiModuleIC' of task ':ktlint-rules:compileKotlin'.
> Invocation of 'Task.project' by task ':ktlint-rules:compileKotlin' at execution time is unsupported with the configuration cache.
```

fix: disable configuration cache

---

.github/actions/jreleaser/action.yml
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt

We recently broke the `jreleaserFullRelease` command and didn't catch it until release time, hence this check.

feat: jreleaser check action

---

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt

Previously we only configured artifact overrides for the K/N targets enabled on the current host. Our publication step tries to  publish all of the artifacts from a single Linux host, so we need to configure macOS and Windows artifact overrides on it too.

fix: configure artifact overrides for all K/N targets

---

.github/actions/changelog-verification/action.yml
.github/workflows/merge-main.yml
CODEOWNERS
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt

Migrate repository references from awslabs to aws organization following GitHub repository transfer.

chore: migrate repo from awslabs to aws

---

build-plugins/kmp-conventions/src/main/kotlin/aws/sdk/kotlin/gradle/kmp/ConfigureTargets.kt

misc: configure Linux for smithy-kotlin

---

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt
build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/publishing/SonatypeCentralPortalWaitForPublicationTask.kt

misc: stop using JReleaser environment variables in `configurePublishing`

---

build-plugins/build-support/src/main/kotlin/aws/sdk/kotlin/gradle/publishing/SonatypeCentralPortalPublishTask.kt

Fix terminal state
